version: '3'
services:

  mysql1:
    image: mysql:5.6.26
    container_name: employees
    command: --max_allowed_packet=1000000000
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_1}
     MYSQL_USER: ${USER_1}
     MYSQL_HOST: ${MYSQL_HOST_1}
     MYSQL_DATABASE: ${DATABASE_1}
    volumes:
      - ./data/sql1:/docker-entrypoint-initdb.d/
    ports:
      - "${DB_PORT_1}:3306"
    env_file:
      - .env

  mysql2:
    image: mysql:5.6.26
    container_name: employees_copy
    command: --max_allowed_packet=1000000000
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_2}
     MYSQL_USER: ${USER_2}
     MYSQL_HOST: ${MYSQL_HOST_2}
     MYSQL_DATABASE: ${DATABASE_2}
    volumes:
      - ./data/sql2:/docker-entrypoint-initdb.d/
    ports:
      - "${DB_PORT_2}:3306"
    env_file:
      - .env

  app:
    container_name: app
    build: .
    volumes:
      - ./code:/code
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - mysql1
      - mysql2
    entrypoint: "bash entrypoint.sh"
    env_file:
      - .env
